import { rm, readdir } from 'node:fs/promises';
import { existsSync, createReadStream, statSync } from 'node:fs';
import { join, basename, resolve, extname } from 'node:path';
import pkg from './package.json' with { type: 'json' };
import { generateThemeManifest, AUDIO_EXT } from './scripts/gen-theme-manifest.mjs';

const MIME = {
  '.mp3': 'audio/mpeg', '.ogg': 'audio/ogg', '.oga': 'audio/ogg', '.m4a': 'audio/mp4',
  '.aac': 'audio/aac', '.wav': 'audio/wav', '.opus': 'audio/opus', '.flac': 'audio/flac',
  '.webm': 'audio/webm',
};

// DEV ONLY: keep src/audio/themeManifest.js in sync with what is actually on
// disk. The manifest is generated by npm's `predev` hook — a ONE-SHOT at server
// start — so both `npx vite` (which bypasses pre* scripts) and, far more often,
// dropping a track into public/theme-music/ while the server is already running
// leave it stale: the file is sitting right there and the player sees an empty
// playlist. The build path already closes this exact hole at buildStart (see
// themeMusicShipGate below); dev needs the same, plus a watcher.
//
function themeMusicDevManifest() {
  return {
    name: 'theme-music-dev-manifest',
    apply: 'serve',
    async configureServer(server) {
      const dirs = [
        join(server.config.root, 'public', 'theme-music'),
        join(server.config.root, 'CC-assets', 'CC-sounds'),
      ];
      const regen = async (why) => {
        try {
          const { count } = await generateThemeManifest({ quiet: true });
          server.config.logger.info(`\x1b[36m  ➜  theme-music: ${count} track(s) — ${why}\x1b[0m`);
        } catch (err) {
          server.config.logger.error(`[theme-music] manifest regen failed: ${err.message}`);
        }
      };
      await regen('generated at startup');

      // Copying several tracks in at once fires one event per file; coalesce so
      // the manifest is written (and the page reloaded) once for the batch.
      let timer = null;
      const touched = (file) => {
        if (!AUDIO_EXT.has(extname(file).toLowerCase())) return;
        if (!dirs.some(d => file.startsWith(d))) return;
        clearTimeout(timer);
        timer = setTimeout(() => regen(`${basename(file)} changed`), 150);
      };
      // public/ is inside root and already watched; CC-assets/ is not, so add it
      // explicitly. Creating that folder mid-session needs a server restart.
      for (const d of dirs) if (existsSync(d)) server.watcher.add(d);
      server.watcher.on('add', touched);
      server.watcher.on('unlink', touched);
      // Rewriting the manifest is itself a module change, so Vite reloads the
      // page and the new playlist takes effect without a restart. No loop: the
      // manifest is a .js outside `dirs`, so it never re-triggers `touched`.
    },
  };
}

// DEV ONLY: serve CC-assets/CC-sounds at /theme-music/*. That folder is a local
// scratch space for tracks you want to hear in dev without adding them to the
// repo — it sits OUTSIDE publicDir and is gitignored, so Vite never copies it
// into a build. Anything you want in a build goes in public/theme-music/.
function themeMusicDevServe() {
  return {
    name: 'theme-music-dev-serve',
    apply: 'serve',
    configureServer(server) {
      const dir = join(server.config.root, 'CC-assets', 'CC-sounds');
      if (!existsSync(dir)) return;
      server.middlewares.use('/theme-music', (req, res, next) => {
        let name;
        try {
          // basename() strips any ../ traversal; decodeURIComponent throws
          // URIError on malformed escapes (e.g. /theme-music/%E0%A4%A)
          name = basename(decodeURIComponent((req.url || '').split('?')[0]));
        } catch { return next(); }
        const file = join(dir, name);
        const dot = name.lastIndexOf('.');
        const ext = dot > 0 ? name.slice(dot).toLowerCase() : '';
        if (!MIME[ext] || !existsSync(file) || !statSync(file).isFile()) return next();
        const { size } = statSync(file);
        const range = req.headers.range;
        res.setHeader('Content-Type', MIME[ext]);
        res.setHeader('Accept-Ranges', 'bytes');
        if (range) {                                  // <audio> streaming needs 206
          const [s, e] = range.replace(/bytes=/, '').split('-');
          const start = parseInt(s, 10) || 0;
          const end = e ? parseInt(e, 10) : size - 1;
          res.statusCode = 206;
          res.setHeader('Content-Range', `bytes ${start}-${end}/${size}`);
          res.setHeader('Content-Length', end - start + 1);
          createReadStream(file, { start, end }).pipe(res);
        } else {
          res.setHeader('Content-Length', size);
          createReadStream(file).pipe(res);
        }
      });
      server.config.logger.info(
        '\x1b[33m  ➜  theme-music: also serving CC-assets/CC-sounds ' +
        '(local scratch — not copied into builds)\x1b[0m');
    },
  };
}

// BUILD: regenerate the manifest with build semantics, and keep dist/theme-music
// to actual audio. Every track in public/theme-music/ ships — there is no
// allowlist and nothing is withheld.
function themeMusicBuild() {
  let outDir = 'dist';
  return {
    name: 'theme-music-build',
    apply: 'build',
    // build.outDir stays RELATIVE ('dist') after resolveConfig — joining it bare
    // would resolve against process.cwd(), so a build launched from any other
    // directory would tidy the wrong path.
    configResolved(cfg) { outDir = resolve(cfg.root, cfg.build.outDir); },
    // Regenerate HERE, not only from the npm `prebuild` hook: `npx vite build`
    // bypasses pre* scripts, and a manifest left over from `npm run dev` would
    // otherwise bake CC-assets/CC-sounds names into the bundle — files Vite
    // never copies to dist/, so every one of those URLs would 404.
    async buildStart() {
      const { count } = await generateThemeManifest({ build: true, quiet: true });
      this.info?.(`[theme-music] ${count} track(s) in the build.`);
    },
    // closeBundle runs after the publicDir → outDir copy has completed.
    async closeBundle() {
      const shipped = join(outDir, 'theme-music');
      if (!existsSync(shipped)) return;
      // README.md is documentation for people dropping tracks in — it belongs in
      // the repo, not on a served copy. Audio is left strictly alone.
      const isAudio = n => AUDIO_EXT.has(extname(n).toLowerCase());
      for (const e of await readdir(shipped, { withFileTypes: true })) {
        if (e.isFile() && !isAudio(e.name)) await rm(join(shipped, e.name), { force: true });
      }
    },
  };
}

export default {
  base: './',
  define: { __APP_VERSION__: JSON.stringify(pkg.version) },
  build: { target: 'es2022' },
  worker: { format: 'es' },   // terrain worker uses ES module imports
  plugins: [themeMusicDevManifest(), themeMusicDevServe(), themeMusicBuild()],
};
